### ISSUE TITLE
"Make Ridges" script not working. 

### ISSUE THREAD

**Issue by BenSmithers** [BenSmithers/MultiHex#24]
The `make_ridges.py` script in the generator doesn't work quite right. The mountain ridges don't follow the sampled direction as they should, and instead just seem to go straight down or zig-zag randomly. 

This needs to be played with!

**Comment by RAMcGuyer** [comment]
Apparently the numbers are off when calculating the odds of a ridge branching off into separate direction. As they are now, they tend to always grow at upwards angles, so they seem to favor the angles of 150 degrees and 90 degrees.
